### ISSUE TITLE
Add `get_filename` method

### ISSUE THREAD

**Issue by notanumber** [wharton/drf-renderer-xlsx#14]
Would it make sense to mirror how most of the DRF & Django's CBVs work by having a `get_` method for `get_filename` that would allow a user to dynamically set the filename when using the `XLSXFileMixin`?

Maybe as simple as:
```
def get_filename(self):
    return self.filename
```

**Comment by FlipperPA** [comment]
Great idea! Can you give this branch a whirl and see if it works for ya?

https://github.com/wharton/drf-renderer-xlsx/tree/feature/get-filename-method

**Comment by FlipperPA** [comment]
BTW, you are @notanumber, you are a free man! 🔢

**Comment by FlipperPA** [comment]
This has been published to PyPI as version 0.3.5.

**Comment by notanumber** [comment]
Looks good, thanks! I'll upgrade and give it a whirl shortly.
