### ISSUE TITLE
Can't download Excel file

### ISSUE THREAD

**Issue by smuglik** [wharton/drf-renderer-xlsx#21]
Hi guys! 

I try to download Excel file but i can't. After send a request I've got some trash in response and I can't download file. Do I need to define download method? 

Here is my view and serializer: 

```
class ReportViewSet(XLSXFileMixin, viewsets.ReadOnlyModelViewSet):
    queryset = models.Item.objects.all()
    serializer_class = serializers.ReportSerializer
    renderer_classes = (XLSXRenderer,)
    filename = 'report.xlsx'

    column_header = {
        'titles': [
            "Column_1_name",
            "Column_2_name",
            "Column_3_name",
        ]
```

```
class ReportSerializer(serializers.Serializer):
    color = serializers.SerializerMethodField()

    def get_color(self, instance):
        color_map = {'w': 'FFFFFFCC', 'a': 'FFFFCCCC'}
        return color_map.get(instance.name, 'FFFFFFFF')
```

Thank you in advance!

**Comment by FlipperPA** [comment]
Howdy! The Mixin should take care of providing a valid HTTP response.

What browser and operating system are you using? Does the browser have any plugins installed? Can you try another browser as well, and let us know if that works? Thanks!

**Comment by smuglik** [comment]
Sorry, that my fault, I really forget about authorization :) 

But, may I ask one more question? How can I fill excel file with my data? I have a queryset, but how can I put it in xlsx?

**Comment by FlipperPA** [comment]
@smuglik The easiest way to see it in action it to use the browsable HTML API for Django REST Framework. Find an endpoint that you like, and use the dropdown to select "XLSX"... or just tack "&format=xlsx" on the end of the URL. :)
