### ISSUE TITLE
Can you please provide a documentation on how to use it with nested serializers?

### ISSUE THREAD

**Issue by grantmatch-ops** [wharton/drf-renderer-xlsx#31]

**Comment by Shin--** [comment]
@grantmatch-ops Do you have any specific questions? I recently rewrote a lot of how we handle and can handle nested serializers (and fields). Maybe the comments already help you: https://github.com/wharton/drf-renderer-xlsx/blob/main/drf_renderer_xlsx/renderers.py

But yes, I (or someone else) should update the readme and explain some more

**Comment by FlipperPA** [comment]
@Shin-- That'd be fantastic if you could put a quick example in the README. Thanks!
