### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by willtho89** [wharton/drf-renderer-xlsx#41]
Hi @FlipperPA 

I would like to help maintain this project (reviewing PRs & creating releases). We use this package quite heavily at my company and it would be great to give back (and maybe speed up the process PR to new release 😉).

**Comment by FlipperPA** [comment]
Hey @willtho89! That sounds amazing. I get to PRs as work allows, so having someone else on board would be great. Want to setup a time to chat so we can talk logistics? You can put time on my calendar here:

https://calendly.com/flipperpa/

**Comment by FlipperPA** [comment]
Closing this out, since we're meeting in half an hour! :)
