### ISSUE TITLE
Syntax Error when using python 3.5

### ISSUE THREAD

**Issue by hweex** [wharton/drf-renderer-xlsx#9]
I got syntax error when using drf-renderer-xlsx. I found the code using f-string which is the new feature of python 3.6. Can I keep on using python 3.5 or the README.md should be updated to Python>=3.6?

**Comment by FlipperPA** [comment]
@hweex I've updated the documentation to say that we're only supporting Python 3.6+ at this point. F-Strings are just too good to miss out on! Older versions will continue to work on Python 3.5. Sorry for any inconvenience.
